steps:
# - name: gcr.io/cloud-builders/docker
#   id: base
#   args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/base', '-f', 'Dockerfile.base', '.']
- name: gcr.io/cloud-builders/docker
  id: training-base
  args: ['build', '-t', 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/training-base', '-f', 'Dockerfile.training-base', '.']
options:
  # since most of the build time is conda (python) setting up the environment
  # we can't take advantage of multiple cpus
  machineType: 'E2_HIGHCPU_8'
images:
- 'us-central1-docker.pkg.dev/md-wbeebe-0808-example-apps/mass-learn/training-base'

